# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import views.icons_rc
from views.components import Slider
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setStyleSheet("background-color: rgb(15, 15, 15);")
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(180, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(180, 16777215))
        self.frame_left_menu.setStyleSheet(
            "background-color: rgb(50, 50, 50);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_icon = QtWidgets.QFrame(self.frame_top_menus)
        self.frame_icon.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_icon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_icon.setStyleSheet(
            "border-bottom: 2px solid rgb(50,50,50);")
        self.frame_icon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_icon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_icon.setObjectName("frame_icon")
        self.verticalLayout_3.addWidget(self.frame_icon)
        self.Btn_Dashboard = QtWidgets.QPushButton(self.frame_top_menus)
        self.Btn_Dashboard.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Btn_Dashboard.setFont(font)
        self.Btn_Dashboard.setStyleSheet("QPushButton {\n"
                                         "    color: rgb(255,255,255);\n"
                                         "     background-color: rgb(50,50,50);\n"
                                         "    border: 0px solid;\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: rgb(85, 170, 255);\n"
                                         "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/home.svg"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Dashboard.setIcon(icon)
        self.Btn_Dashboard.setObjectName("Btn_Dashboard")
        self.verticalLayout_3.addWidget(self.Btn_Dashboard)
        self.Btn_Library = QtWidgets.QPushButton(self.frame_top_menus)
        self.Btn_Library.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Btn_Library.setFont(font)
        self.Btn_Library.setStyleSheet("QPushButton {\n"
                                       "    color: rgb(255,255,255);\n"
                                       "     background-color: rgb(50,50,50);\n"
                                       "    border: 0px solid;\n"
                                       "}\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: rgb(85, 170, 255);\n"
                                       "}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/list.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Library.setIcon(icon1)
        self.Btn_Library.setObjectName("Btn_Library")
        self.verticalLayout_3.addWidget(self.Btn_Library)
        self.Btn_Add_Playlist = QtWidgets.QPushButton(self.frame_top_menus)
        self.Btn_Add_Playlist.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Btn_Add_Playlist.setFont(font)
        self.Btn_Add_Playlist.setStyleSheet("QPushButton {\n"
                                            "    color: rgb(255,255,255);\n"
                                            "     background-color: rgb(50,50,50);\n"
                                            "    border: 0px solid;\n"
                                            "}\n"
                                            "QPushButton:hover {\n"
                                            "    background-color: rgb(85, 170, 255);\n"
                                            "}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/plus-square.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Add_Playlist.setIcon(icon2)
        self.Btn_Add_Playlist.setObjectName("Btn_Add_Playlist")
        self.verticalLayout_3.addWidget(self.Btn_Add_Playlist)
        self.listWidget_playlists = QtWidgets.QListWidget(self.frame_top_menus)
        self.listWidget_playlists.setMinimumSize(QtCore.QSize(0, 200))
        self.listWidget_playlists.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.listWidget_playlists.setFont(font)
        self.listWidget_playlists.setStyleSheet("color: #FFF; \n"
                                                "QListWidget::item:selected {\n"
                                                "     background: transparent;\n"
                                                "    border: 0px solid;\n"
                                                "}")
        self.listWidget_playlists.setObjectName("listWidget_playlists")
        self.verticalLayout_3.addWidget(self.listWidget_playlists)
        self.Btn_Settings = QtWidgets.QPushButton(self.frame_top_menus)
        self.Btn_Settings.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Btn_Settings.setFont(font)
        self.Btn_Settings.setStyleSheet("QPushButton {\n"
                                        "    color: rgb(255,255,255);\n"
                                        "     background-color: rgb(50,50,50);\n"
                                        "    border: 0px solid;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(85, 170, 255);\n"
                                        "}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/settings.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Settings.setIcon(icon3)
        self.Btn_Settings.setObjectName("Btn_Settings")
        self.verticalLayout_3.addWidget(self.Btn_Settings)
        self.verticalLayout_2.addWidget(self.frame_top_menus)
        self.horizontalLayout.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Pages_Widget = QtWidgets.QStackedWidget(self.frame_pages)
        self.Pages_Widget.setObjectName("Pages_Widget")
        self.page_dashboard = QtWidgets.QWidget()
        self.page_dashboard.setObjectName("page_dashboard")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_dashboard)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_dashboard = QtWidgets.QFrame(self.page_dashboard)
        self.frame_dashboard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_dashboard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_dashboard.setObjectName("frame_dashboard")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_dashboard)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_dashboard = QtWidgets.QLabel(self.frame_dashboard)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_dashboard.setFont(font)
        self.label_dashboard.setStyleSheet("color: #FFF;")
        self.label_dashboard.setObjectName("label_dashboard")
        self.verticalLayout_6.addWidget(self.label_dashboard)
        self.Btn_menu_add_songs = QtWidgets.QPushButton(self.frame_dashboard)
        self.Btn_menu_add_songs.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Btn_menu_add_songs.setFont(font)
        self.Btn_menu_add_songs.setStyleSheet("QPushButton {\n"
                                              "    color: rgb(255,255,255);\n"
                                              "     background-color: rgb(45,45,45);\n"
                                              "    border: 0px solid;\n"
                                              "}\n"
                                              "QPushButton:hover {\n"
                                              "    background-color: rgb(85, 170, 255);\n"
                                              "}")
        self.Btn_menu_add_songs.setObjectName("Btn_menu_add_songs")
        self.verticalLayout_6.addWidget(self.Btn_menu_add_songs)
        self.Btn_menu_fer = QtWidgets.QPushButton(self.frame_dashboard)
        self.Btn_menu_fer.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Btn_menu_fer.setFont(font)
        self.Btn_menu_fer.setStyleSheet("QPushButton {\n"
                                        "    color: rgb(255,255,255);\n"
                                        "     background-color: rgb(45,45,45);\n"
                                        "    border: 0px solid;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(85, 170, 255);\n"
                                        "}")
        self.Btn_menu_fer.setObjectName("Btn_menu_fer")
        self.verticalLayout_6.addWidget(self.Btn_menu_fer)
        self.Btn_menu_settings = QtWidgets.QPushButton(self.frame_dashboard)
        self.Btn_menu_settings.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Btn_menu_settings.setFont(font)
        self.Btn_menu_settings.setStyleSheet("QPushButton {\n"
                                             "    color: rgb(255,255,255);\n"
                                             "     background-color: rgb(45,45,45);\n"
                                             "    border: 0px solid;\n"
                                             "}\n"
                                             "QPushButton:hover {\n"
                                             "    background-color: rgb(85, 170, 255);\n"
                                             "}")
        self.Btn_menu_settings.setObjectName("Btn_menu_settings")
        self.verticalLayout_6.addWidget(self.Btn_menu_settings)
        self.verticalLayout_7.addWidget(self.frame_dashboard)
        self.Pages_Widget.addWidget(self.page_dashboard)
        self.page_emotion_recognition = QtWidgets.QWidget()
        self.page_emotion_recognition.setObjectName("page_emotion_recognition")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(
            self.page_emotion_recognition)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_emotion_recognition = QtWidgets.QFrame(
            self.page_emotion_recognition)
        self.frame_emotion_recognition.setFrameShape(
            QtWidgets.QFrame.StyledPanel)
        self.frame_emotion_recognition.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_emotion_recognition.setObjectName(
            "frame_emotion_recognition")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(
            self.frame_emotion_recognition)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_emotion_recognition = QtWidgets.QLabel(
            self.frame_emotion_recognition)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_emotion_recognition.setFont(font)
        self.label_emotion_recognition.setStyleSheet("color: #FFF;")
        self.label_emotion_recognition.setObjectName(
            "label_emotion_recognition")
        self.verticalLayout_16.addWidget(self.label_emotion_recognition)
        self.label_fer_result = QtWidgets.QLabel(
            self.frame_emotion_recognition)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_fer_result.setFont(font)
        self.label_fer_result.setStyleSheet("color: #FFF;")
        self.label_fer_result.setObjectName("label_fer_result")
        self.verticalLayout_16.addWidget(self.label_fer_result)
        self.verticalLayout_17.addWidget(self.frame_emotion_recognition)
        self.Pages_Widget.addWidget(self.page_emotion_recognition)
        self.page_emotion_recognition_no_playlist = QtWidgets.QWidget()
        self.page_emotion_recognition_no_playlist.setObjectName(
            "page_emotion_recognition_no_playlist")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(
            self.page_emotion_recognition_no_playlist)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_emotion_recognition_no_playlist = QtWidgets.QFrame(
            self.page_emotion_recognition_no_playlist)
        self.frame_emotion_recognition_no_playlist.setFrameShape(
            QtWidgets.QFrame.StyledPanel)
        self.frame_emotion_recognition_no_playlist.setFrameShadow(
            QtWidgets.QFrame.Raised)
        self.frame_emotion_recognition_no_playlist.setObjectName(
            "frame_emotion_recognition_no_playlist")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(
            self.frame_emotion_recognition_no_playlist)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_emotion_recognition_no_playlist = QtWidgets.QLabel(
            self.frame_emotion_recognition_no_playlist)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_emotion_recognition_no_playlist.setFont(font)
        self.label_emotion_recognition_no_playlist.setStyleSheet(
            "color: #FFF;")
        self.label_emotion_recognition_no_playlist.setObjectName(
            "label_emotion_recognition_no_playlist")
        self.verticalLayout_5.addWidget(
            self.label_emotion_recognition_no_playlist)
        self.label_fer_result_no_playlist = QtWidgets.QLabel(
            self.frame_emotion_recognition_no_playlist)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_fer_result_no_playlist.setFont(font)
        self.label_fer_result_no_playlist.setStyleSheet("color: #FFF;")
        self.label_fer_result_no_playlist.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fer_result_no_playlist.setWordWrap(True)
        self.label_fer_result_no_playlist.setObjectName(
            "label_fer_result_no_playlist")
        self.verticalLayout_5.addWidget(self.label_fer_result_no_playlist)
        self.btn_go_to_settings_no_playlist = QtWidgets.QPushButton(
            self.frame_emotion_recognition_no_playlist)
        self.btn_go_to_settings_no_playlist.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_go_to_settings_no_playlist.setMaximumSize(
            QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_go_to_settings_no_playlist.setFont(font)
        self.btn_go_to_settings_no_playlist.setStyleSheet("QPushButton {\n"
                                                          "    color: rgb(255,255,255);\n"
                                                          "     background-color: rgb(50,50,50);\n"
                                                          "    border: 0px solid;\n"
                                                          "}\n"
                                                          "QPushButton:hover {\n"
                                                          "    background-color: rgb(85, 170, 255);\n"
                                                          "}")
        self.btn_go_to_settings_no_playlist.setObjectName(
            "btn_go_to_settings_no_playlist")
        self.verticalLayout_5.addWidget(self.btn_go_to_settings_no_playlist)
        self.horizontalLayout_13.addWidget(
            self.frame_emotion_recognition_no_playlist)
        self.Pages_Widget.addWidget(self.page_emotion_recognition_no_playlist)
        self.page_emotion_recognition_loading = QtWidgets.QWidget()
        self.page_emotion_recognition_loading.setObjectName(
            "page_emotion_recognition_loading")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(
            self.page_emotion_recognition_loading)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_emotion_recognition_loading = QtWidgets.QFrame(
            self.page_emotion_recognition_loading)
        self.frame_emotion_recognition_loading.setFrameShape(
            QtWidgets.QFrame.StyledPanel)
        self.frame_emotion_recognition_loading.setFrameShadow(
            QtWidgets.QFrame.Raised)
        self.frame_emotion_recognition_loading.setObjectName(
            "frame_emotion_recognition_loading")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(
            self.frame_emotion_recognition_loading)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_emotion_recognition_loading = QtWidgets.QLabel(
            self.frame_emotion_recognition_loading)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_emotion_recognition_loading.setFont(font)
        self.label_emotion_recognition_loading.setStyleSheet("color: #FFF;")
        self.label_emotion_recognition_loading.setObjectName(
            "label_emotion_recognition_loading")
        self.verticalLayout_8.addWidget(self.label_emotion_recognition_loading)
        self.label_emotion_recognition_info_loading = QtWidgets.QLabel(
            self.frame_emotion_recognition_loading)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_emotion_recognition_info_loading.setFont(font)
        self.label_emotion_recognition_info_loading.setStyleSheet(
            "color: #FFF;")
        self.label_emotion_recognition_info_loading.setAlignment(
            QtCore.Qt.AlignCenter)
        self.label_emotion_recognition_info_loading.setWordWrap(True)
        self.label_emotion_recognition_info_loading.setObjectName(
            "label_emotion_recognition_info_loading")
        self.verticalLayout_8.addWidget(
            self.label_emotion_recognition_info_loading)
        self.frame_emotion_recognition_loading_orb = QtWidgets.QFrame(
            self.frame_emotion_recognition_loading)
        self.frame_emotion_recognition_loading_orb.setMinimumSize(
            QtCore.QSize(0, 200))
        self.frame_emotion_recognition_loading_orb.setFrameShape(
            QtWidgets.QFrame.StyledPanel)
        self.frame_emotion_recognition_loading_orb.setFrameShadow(
            QtWidgets.QFrame.Raised)
        self.frame_emotion_recognition_loading_orb.setObjectName(
            "frame_emotion_recognition_loading_orb")
        self.verticalLayout_8.addWidget(
            self.frame_emotion_recognition_loading_orb)
        self.verticalLayout_12.addWidget(
            self.frame_emotion_recognition_loading)
        self.Pages_Widget.addWidget(self.page_emotion_recognition_loading)
        self.page_settings = QtWidgets.QWidget()
        self.page_settings.setObjectName("page_settings")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.page_settings)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_settings = QtWidgets.QFrame(self.page_settings)
        self.frame_settings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_settings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_settings.setObjectName("frame_settings")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_settings)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_dashboard_2 = QtWidgets.QLabel(self.frame_settings)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_dashboard_2.setFont(font)
        self.label_dashboard_2.setStyleSheet("color: #FFF;")
        self.label_dashboard_2.setObjectName("label_dashboard_2")
        self.verticalLayout_14.addWidget(self.label_dashboard_2)
        self.Btn_settings_hand_gesture = QtWidgets.QPushButton(
            self.frame_settings)
        self.Btn_settings_hand_gesture.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Btn_settings_hand_gesture.setFont(font)
        self.Btn_settings_hand_gesture.setStyleSheet("QPushButton {\n"
                                                     "    color: rgb(255,255,255);\n"
                                                     "     background-color: rgb(45,45,45);\n"
                                                     "    border: 0px solid;\n"
                                                     "}\n"
                                                     "QPushButton:hover {\n"
                                                     "    background-color: rgb(85, 170, 255);\n"
                                                     "}")
        self.Btn_settings_hand_gesture.setObjectName(
            "Btn_settings_hand_gesture")
        self.verticalLayout_14.addWidget(self.Btn_settings_hand_gesture)
        self.Btn_settings_emotion_map = QtWidgets.QPushButton(
            self.frame_settings)
        self.Btn_settings_emotion_map.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Btn_settings_emotion_map.setFont(font)
        self.Btn_settings_emotion_map.setStyleSheet("QPushButton {\n"
                                                    "    color: rgb(255,255,255);\n"
                                                    "     background-color: rgb(45,45,45);\n"
                                                    "    border: 0px solid;\n"
                                                    "}\n"
                                                    "QPushButton:hover {\n"
                                                    "    background-color: rgb(85, 170, 255);\n"
                                                    "}")
        self.Btn_settings_emotion_map.setObjectName("Btn_settings_emotion_map")
        self.verticalLayout_14.addWidget(self.Btn_settings_emotion_map)
        self.Btn_settings_bluetooth = QtWidgets.QPushButton(
            self.frame_settings)
        self.Btn_settings_bluetooth.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Btn_settings_bluetooth.setFont(font)
        self.Btn_settings_bluetooth.setStyleSheet("QPushButton {\n"
                                                  "    color: rgb(255,255,255);\n"
                                                  "     background-color: rgb(45,45,45);\n"
                                                  "    border: 0px solid;\n"
                                                  "}\n"
                                                  "QPushButton:hover {\n"
                                                  "    background-color: rgb(85, 170, 255);\n"
                                                  "}")
        self.Btn_settings_bluetooth.setObjectName("Btn_settings_bluetooth")
        self.verticalLayout_14.addWidget(self.Btn_settings_bluetooth)
        self.verticalLayout_15.addWidget(self.frame_settings)
        self.Pages_Widget.addWidget(self.page_settings)
        self.page_settings_emotion_playlist_map = QtWidgets.QWidget()
        self.page_settings_emotion_playlist_map.setObjectName(
            "page_settings_emotion_playlist_map")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(
            self.page_settings_emotion_playlist_map)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.frame_settings_emotion_playlist_map = QtWidgets.QFrame(
            self.page_settings_emotion_playlist_map)
        self.frame_settings_emotion_playlist_map.setFrameShape(
            QtWidgets.QFrame.StyledPanel)
        self.frame_settings_emotion_playlist_map.setFrameShadow(
            QtWidgets.QFrame.Raised)
        self.frame_settings_emotion_playlist_map.setObjectName(
            "frame_settings_emotion_playlist_map")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(
            self.frame_settings_emotion_playlist_map)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_settings_hand_gesture_2 = QtWidgets.QLabel(
            self.frame_settings_emotion_playlist_map)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_settings_hand_gesture_2.setFont(font)
        self.label_settings_hand_gesture_2.setStyleSheet("color: #FFF;")
        self.label_settings_hand_gesture_2.setObjectName(
            "label_settings_hand_gesture_2")
        self.verticalLayout_23.addWidget(self.label_settings_hand_gesture_2)
        self.frame_settings_emotion_playlist_map_content = QtWidgets.QFrame(
            self.frame_settings_emotion_playlist_map)
        self.frame_settings_emotion_playlist_map_content.setStyleSheet(
            "background-color: rgb(35,35,35);")
        self.frame_settings_emotion_playlist_map_content.setFrameShape(
            QtWidgets.QFrame.StyledPanel)
        self.frame_settings_emotion_playlist_map_content.setFrameShadow(
            QtWidgets.QFrame.Raised)
        self.frame_settings_emotion_playlist_map_content.setObjectName(
            "frame_settings_emotion_playlist_map_content")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(
            self.frame_settings_emotion_playlist_map_content)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frame_settings_emotion_playlist_map_content_happy = QtWidgets.QFrame(
            self.frame_settings_emotion_playlist_map_content)
        self.frame_settings_emotion_playlist_map_content_happy.setMinimumSize(
            QtCore.QSize(0, 60))
        self.frame_settings_emotion_playlist_map_content_happy.setFrameShape(
            QtWidgets.QFrame.StyledPanel)
        self.frame_settings_emotion_playlist_map_content_happy.setFrameShadow(
            QtWidgets.QFrame.Raised)
        self.frame_settings_emotion_playlist_map_content_happy.setObjectName(
            "frame_settings_emotion_playlist_map_content_happy")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(
            self.frame_settings_emotion_playlist_map_content_happy)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_settings_emotion_playlist_map_happy = QtWidgets.QLabel(
            self.frame_settings_emotion_playlist_map_content_happy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_settings_emotion_playlist_map_happy.setFont(font)
        self.label_settings_emotion_playlist_map_happy.setStyleSheet(
            "color: #FFF;")
        self.label_settings_emotion_playlist_map_happy.setObjectName(
            "label_settings_emotion_playlist_map_happy")
        self.horizontalLayout_3.addWidget(
            self.label_settings_emotion_playlist_map_happy)
        self.comboBox_settings_emotion_playlist_map_happy = QtWidgets.QComboBox(
            self.frame_settings_emotion_playlist_map_content_happy)
        self.comboBox_settings_emotion_playlist_map_happy.setObjectName(
            "comboBox_settings_emotion_playlist_map_happy")
        self.horizontalLayout_3.addWidget(
            self.comboBox_settings_emotion_playlist_map_happy)
        self.verticalLayout_24.addWidget(
            self.frame_settings_emotion_playlist_map_content_happy)
        self.frame_settings_emotion_playlist_map_content_sad = QtWidgets.QFrame(
            self.frame_settings_emotion_playlist_map_content)
        self.frame_settings_emotion_playlist_map_content_sad.setMinimumSize(
            QtCore.QSize(0, 60))
        self.frame_settings_emotion_playlist_map_content_sad.setFrameShape(
            QtWidgets.QFrame.StyledPanel)
        self.frame_settings_emotion_playlist_map_content_sad.setFrameShadow(
            QtWidgets.QFrame.Raised)
        self.frame_settings_emotion_playlist_map_content_sad.setObjectName(
            "frame_settings_emotion_playlist_map_content_sad")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(
            self.frame_settings_emotion_playlist_map_content_sad)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_settings_emotion_playlist_map_sad = QtWidgets.QLabel(
            self.frame_settings_emotion_playlist_map_content_sad)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_settings_emotion_playlist_map_sad.setFont(font)
        self.label_settings_emotion_playlist_map_sad.setStyleSheet(
            "color: #FFF;")
        self.label_settings_emotion_playlist_map_sad.setObjectName(
            "label_settings_emotion_playlist_map_sad")
        self.horizontalLayout_4.addWidget(
            self.label_settings_emotion_playlist_map_sad)
        self.comboBox_settings_emotion_playlist_map_sad = QtWidgets.QComboBox(
            self.frame_settings_emotion_playlist_map_content_sad)
        self.comboBox_settings_emotion_playlist_map_sad.setObjectName(
            "comboBox_settings_emotion_playlist_map_sad")
        self.horizontalLayout_4.addWidget(
            self.comboBox_settings_emotion_playlist_map_sad)
        self.verticalLayout_24.addWidget(
            self.frame_settings_emotion_playlist_map_content_sad)
        self.frame_settings_emotion_playlist_map_content_angry = QtWidgets.QFrame(
            self.frame_settings_emotion_playlist_map_content)
        self.frame_settings_emotion_playlist_map_content_angry.setMinimumSize(
            QtCore.QSize(0, 60))
        self.frame_settings_emotion_playlist_map_content_angry.setFrameShape(
            QtWidgets.QFrame.StyledPanel)
        self.frame_settings_emotion_playlist_map_content_angry.setFrameShadow(
            QtWidgets.QFrame.Raised)
        self.frame_settings_emotion_playlist_map_content_angry.setObjectName(
            "frame_settings_emotion_playlist_map_content_angry")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(
            self.frame_settings_emotion_playlist_map_content_angry)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_settings_emotion_playlist_map_angry = QtWidgets.QLabel(
            self.frame_settings_emotion_playlist_map_content_angry)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_settings_emotion_playlist_map_angry.setFont(font)
        self.label_settings_emotion_playlist_map_angry.setStyleSheet(
            "color: #FFF;")
        self.label_settings_emotion_playlist_map_angry.setObjectName(
            "label_settings_emotion_playlist_map_angry")
        self.horizontalLayout_7.addWidget(
            self.label_settings_emotion_playlist_map_angry)
        self.comboBox_settings_emotion_playlist_map_angry = QtWidgets.QComboBox(
            self.frame_settings_emotion_playlist_map_content_angry)
        self.comboBox_settings_emotion_playlist_map_angry.setObjectName(
            "comboBox_settings_emotion_playlist_map_angry")
        self.horizontalLayout_7.addWidget(
            self.comboBox_settings_emotion_playlist_map_angry)
        self.verticalLayout_24.addWidget(
            self.frame_settings_emotion_playlist_map_content_angry)
        self.frame_settings_emotion_playlist_map_content_surprise = QtWidgets.QFrame(
            self.frame_settings_emotion_playlist_map_content)
        self.frame_settings_emotion_playlist_map_content_surprise.setMinimumSize(
            QtCore.QSize(0, 60))
        self.frame_settings_emotion_playlist_map_content_surprise.setFrameShape(
            QtWidgets.QFrame.StyledPanel)
        self.frame_settings_emotion_playlist_map_content_surprise.setFrameShadow(
            QtWidgets.QFrame.Raised)
        self.frame_settings_emotion_playlist_map_content_surprise.setObjectName(
            "frame_settings_emotion_playlist_map_content_surprise")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(
            self.frame_settings_emotion_playlist_map_content_surprise)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_settings_emotion_playlist_map_surprise = QtWidgets.QLabel(
            self.frame_settings_emotion_playlist_map_content_surprise)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_settings_emotion_playlist_map_surprise.setFont(font)
        self.label_settings_emotion_playlist_map_surprise.setStyleSheet(
            "color: #FFF;")
        self.label_settings_emotion_playlist_map_surprise.setObjectName(
            "label_settings_emotion_playlist_map_surprise")
        self.horizontalLayout_6.addWidget(
            self.label_settings_emotion_playlist_map_surprise)
        self.comboBox_settings_emotion_playlist_map_surprise = QtWidgets.QComboBox(
            self.frame_settings_emotion_playlist_map_content_surprise)
        self.comboBox_settings_emotion_playlist_map_surprise.setObjectName(
            "comboBox_settings_emotion_playlist_map_surprise")
        self.horizontalLayout_6.addWidget(
            self.comboBox_settings_emotion_playlist_map_surprise)
        self.verticalLayout_24.addWidget(
            self.frame_settings_emotion_playlist_map_content_surprise)
        self.frame_settings_emotion_playlist_map_content_neutral = QtWidgets.QFrame(
            self.frame_settings_emotion_playlist_map_content)
        self.frame_settings_emotion_playlist_map_content_neutral.setMinimumSize(
            QtCore.QSize(0, 60))
        self.frame_settings_emotion_playlist_map_content_neutral.setFrameShape(
            QtWidgets.QFrame.StyledPanel)
        self.frame_settings_emotion_playlist_map_content_neutral.setFrameShadow(
            QtWidgets.QFrame.Raised)
        self.frame_settings_emotion_playlist_map_content_neutral.setObjectName(
            "frame_settings_emotion_playlist_map_content_neutral")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(
            self.frame_settings_emotion_playlist_map_content_neutral)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_settings_emotion_playlist_map_neutral = QtWidgets.QLabel(
            self.frame_settings_emotion_playlist_map_content_neutral)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_settings_emotion_playlist_map_neutral.setFont(font)
        self.label_settings_emotion_playlist_map_neutral.setStyleSheet(
            "color: #FFF;")
        self.label_settings_emotion_playlist_map_neutral.setObjectName(
            "label_settings_emotion_playlist_map_neutral")
        self.horizontalLayout_8.addWidget(
            self.label_settings_emotion_playlist_map_neutral)
        self.comboBox_settings_emotion_playlist_map_neutral = QtWidgets.QComboBox(
            self.frame_settings_emotion_playlist_map_content_neutral)
        self.comboBox_settings_emotion_playlist_map_neutral.setObjectName(
            "comboBox_settings_emotion_playlist_map_neutral")
        self.horizontalLayout_8.addWidget(
            self.comboBox_settings_emotion_playlist_map_neutral)
        self.verticalLayout_24.addWidget(
            self.frame_settings_emotion_playlist_map_content_neutral)
        self.verticalLayout_23.addWidget(
            self.frame_settings_emotion_playlist_map_content)
        self.verticalLayout_25.addWidget(
            self.frame_settings_emotion_playlist_map)
        self.Pages_Widget.addWidget(self.page_settings_emotion_playlist_map)
        self.comboBox_settings_emotion_playlist_map_happy.setStyleSheet(
            "color: #FFF;\n"
            "QComboBox QListView { color: #FFF; }"
        )
        self.comboBox_settings_emotion_playlist_map_angry.setStyleSheet(
            "color: #FFF;\n"
            "QComboBox QListView { color: #FFF; }"
        )
        self.comboBox_settings_emotion_playlist_map_sad.setStyleSheet(
            "color: #FFF;\n"
            "QComboBox QListView { color: #FFF; }"
        )
        self.comboBox_settings_emotion_playlist_map_surprise.setStyleSheet(
            "color: #FFF;\n"
            "QComboBox QListView { color: #FFF; }"
        )
        self.comboBox_settings_emotion_playlist_map_neutral.setStyleSheet(
            "color: #FFF;\n"
            "QComboBox QListView { color: #FFF; }"
        )
        self.page_settings_hand_gesture = QtWidgets.QWidget()
        self.page_settings_hand_gesture.setObjectName(
            "page_settings_hand_gesture")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(
            self.page_settings_hand_gesture)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame_settings_hand_gesture = QtWidgets.QFrame(
            self.page_settings_hand_gesture)
        self.frame_settings_hand_gesture.setFrameShape(
            QtWidgets.QFrame.StyledPanel)
        self.frame_settings_hand_gesture.setFrameShadow(
            QtWidgets.QFrame.Raised)
        self.frame_settings_hand_gesture.setObjectName(
            "frame_settings_hand_gesture")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(
            self.frame_settings_hand_gesture)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_settings_hand_gesture = QtWidgets.QLabel(
            self.frame_settings_hand_gesture)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_settings_hand_gesture.setFont(font)
        self.label_settings_hand_gesture.setStyleSheet("color: #FFF;")
        self.label_settings_hand_gesture.setObjectName(
            "label_settings_hand_gesture")
        self.verticalLayout_20.addWidget(self.label_settings_hand_gesture)
        self.frame_settings_hand_gesture_content = QtWidgets.QFrame(
            self.frame_settings_hand_gesture)
        self.frame_settings_hand_gesture_content.setFrameShape(
            QtWidgets.QFrame.StyledPanel)
        self.frame_settings_hand_gesture_content.setFrameShadow(
            QtWidgets.QFrame.Raised)
        self.frame_settings_hand_gesture_content.setObjectName(
            "frame_settings_hand_gesture_content")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(
            self.frame_settings_hand_gesture_content)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.btn_settings_enable_hand_gesture = QtWidgets.QRadioButton(
            self.frame_settings_hand_gesture_content)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_settings_enable_hand_gesture.setFont(font)
        self.btn_settings_enable_hand_gesture.setStyleSheet("color: #FFF")
        self.btn_settings_enable_hand_gesture.setObjectName(
            "btn_settings_enable_hand_gesture")
        self.verticalLayout_21.addWidget(self.btn_settings_enable_hand_gesture)
        self.verticalLayout_20.addWidget(
            self.frame_settings_hand_gesture_content)
        self.verticalLayout_22.addWidget(self.frame_settings_hand_gesture)
        self.Pages_Widget.addWidget(self.page_settings_hand_gesture)
        self.page_settings_bluetooth = QtWidgets.QWidget()
        self.page_settings_bluetooth.setObjectName("page_settings_bluetooth")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(
            self.page_settings_bluetooth)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_settings_bluetooth = QtWidgets.QFrame(
            self.page_settings_bluetooth)
        self.frame_settings_bluetooth.setFrameShape(
            QtWidgets.QFrame.StyledPanel)
        self.frame_settings_bluetooth.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_settings_bluetooth.setObjectName("frame_settings_bluetooth")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(
            self.frame_settings_bluetooth)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_settings_bluetooth = QtWidgets.QLabel(
            self.frame_settings_bluetooth)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_settings_bluetooth.setFont(font)
        self.label_settings_bluetooth.setStyleSheet("color: #FFF;")
        self.label_settings_bluetooth.setObjectName("label_settings_bluetooth")
        self.verticalLayout_18.addWidget(self.label_settings_bluetooth)
        self.frame_settings_bluetooth_content = QtWidgets.QFrame(
            self.frame_settings_bluetooth)
        self.frame_settings_bluetooth_content.setMinimumSize(
            QtCore.QSize(0, 60))
        self.frame_settings_bluetooth_content.setFrameShape(
            QtWidgets.QFrame.StyledPanel)
        self.frame_settings_bluetooth_content.setFrameShadow(
            QtWidgets.QFrame.Raised)
        self.frame_settings_bluetooth_content.setObjectName(
            "frame_settings_bluetooth_content")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(
            self.frame_settings_bluetooth_content)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_settings_bluetooth_scan_devices = QtWidgets.QPushButton(
            self.frame_settings_bluetooth_content)
        self.btn_settings_bluetooth_scan_devices.setMinimumSize(
            QtCore.QSize(100, 50))
        self.btn_settings_bluetooth_scan_devices.setMaximumSize(
            QtCore.QSize(16777215, 16777215))
        self.btn_settings_bluetooth_scan_devices.setStyleSheet("QPushButton {\n"
                                                               "    color: rgb(255,255,255);\n"
                                                               "     background-color: rgb(35,35,35);\n"
                                                               "    border: 0px solid;\n"
                                                               "}\n"
                                                               "QPushButton:hover {\n"
                                                               "    background-color: rgb(85, 170, 255);\n"
                                                               "}")
        self.btn_settings_bluetooth_scan_devices.setObjectName(
            "btn_settings_bluetooth_scan_devices")
        self.horizontalLayout_5.addWidget(
            self.btn_settings_bluetooth_scan_devices)
        self.btn_settings_bluetooth_disconnect = QtWidgets.QPushButton(
            self.frame_settings_bluetooth_content)
        self.btn_settings_bluetooth_disconnect.setMinimumSize(
            QtCore.QSize(100, 50))
        self.btn_settings_bluetooth_disconnect.setMaximumSize(
            QtCore.QSize(100, 16777215))
        self.btn_settings_bluetooth_disconnect.setStyleSheet("QPushButton {\n"
                                                             "    color: rgb(255,255,255);\n"
                                                             "     background-color: rgb(35,35,35);\n"
                                                             "    border: 0px solid;\n"
                                                             "}\n"
                                                             "QPushButton:hover {\n"
                                                             "    background-color: rgb(85, 170, 255);\n"
                                                             "}")
        self.btn_settings_bluetooth_disconnect.setObjectName(
            "btn_settings_bluetooth_disconnect")
        self.horizontalLayout_5.addWidget(
            self.btn_settings_bluetooth_disconnect)
        self.verticalLayout_18.addWidget(
            self.frame_settings_bluetooth_content, 0, QtCore.Qt.AlignLeft)
        self.listWidget_settings_bluetooth_devices = QtWidgets.QListWidget(
            self.frame_settings_bluetooth)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.listWidget_settings_bluetooth_devices.setFont(font)
        self.listWidget_settings_bluetooth_devices.setObjectName(
            "listWidget_settings_bluetooth_devices")
        self.listWidget_settings_bluetooth_devices.setStyleSheet("QListWidget::item:selected {\n"
                                                                 "     background: transparent;\n"
                                                                 "    border: 0px solid;\n"
                                                                 "}")
        self.verticalLayout_18.addWidget(
            self.listWidget_settings_bluetooth_devices)
        self.verticalLayout_19.addWidget(self.frame_settings_bluetooth)
        self.Pages_Widget.addWidget(self.page_settings_bluetooth)
        self.page_library = QtWidgets.QWidget()
        self.page_library.setObjectName("page_library")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_library)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_library = QtWidgets.QFrame(self.page_library)
        self.frame_library.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_library.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_library.setObjectName("frame_library")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_library)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_library = QtWidgets.QLabel(self.frame_library)
        self.label_library.setEnabled(True)
        self.label_library.setMinimumSize(QtCore.QSize(0, 60))
        self.label_library.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_library.setFont(font)
        self.label_library.setStyleSheet("color: #FFF;")
        self.label_library.setObjectName("label_library")
        self.verticalLayout_10.addWidget(self.label_library)
        self.listWidget_library_songs = QtWidgets.QListWidget(
            self.frame_library)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.listWidget_library_songs.setFont(font)
        # self.listWidget_library_songs.setStyleSheet("color: #FFF;")
        self.listWidget_library_songs.setStyleSheet("color: #FFF; \n"
                                                    "QListWidget::item:selected {\n"
                                                    "     background: transparent;\n"
                                                    "    border: 0px solid;\n"
                                                    "}")
        self.listWidget_library_songs.setObjectName("listWidget_library_songs")
        self.verticalLayout_10.addWidget(self.listWidget_library_songs)
        self.verticalLayout_9.addWidget(self.frame_library)
        self.Pages_Widget.addWidget(self.page_library)
        self.page_playlist_1 = QtWidgets.QWidget()
        self.page_playlist_1.setObjectName("page_playlist_1")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_playlist_1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_playlist = QtWidgets.QFrame(self.page_playlist_1)
        self.frame_playlist.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_playlist.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_playlist.setObjectName("frame_playlist")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_playlist)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_playlist_name = QtWidgets.QLabel(self.frame_playlist)
        self.label_playlist_name.setEnabled(True)
        self.label_playlist_name.setMinimumSize(QtCore.QSize(0, 60))
        self.label_playlist_name.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_playlist_name.setFont(font)
        self.label_playlist_name.setStyleSheet("color: #FFF;")
        self.label_playlist_name.setObjectName("label_playlist_name")
        self.verticalLayout_11.addWidget(self.label_playlist_name)
        self.frame_playlist_buttons = QtWidgets.QFrame(self.frame_playlist)
        self.frame_playlist_buttons.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_playlist_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_playlist_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_playlist_buttons.setObjectName("frame_playlist_buttons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(
            self.frame_playlist_buttons)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_playlist_play = QtWidgets.QPushButton(
            self.frame_playlist_buttons)
        self.btn_playlist_play.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_playlist_play.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_playlist_play.setStyleSheet("QPushButton {\n"
                                             "    color: rgb(255,255,255);\n"
                                             "     background-color: rgb(35,35,35);\n"
                                             "    border: 0px solid;\n"
                                             "}\n"
                                             "QPushButton:hover {\n"
                                             "    background-color: rgb(85, 170, 255);\n"
                                             "}")
        self.btn_playlist_play.setObjectName("btn_playlist_play")
        self.horizontalLayout_2.addWidget(self.btn_playlist_play)
        self.btn_playlist_remove = QtWidgets.QPushButton(
            self.frame_playlist_buttons)
        self.btn_playlist_remove.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_playlist_remove.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_playlist_remove.setStyleSheet("QPushButton {\n"
                                               "    color: rgb(255,255,255);\n"
                                               "     background-color: rgb(35,35,35);\n"
                                               "    border: 0px solid;\n"
                                               "}\n"
                                               "QPushButton:hover {\n"
                                               "    background-color: rgb(85, 170, 255);\n"
                                               "}")
        self.btn_playlist_remove.setObjectName("btn_playlist_remove")
        self.horizontalLayout_2.addWidget(self.btn_playlist_remove)
        self.verticalLayout_11.addWidget(
            self.frame_playlist_buttons, 0, QtCore.Qt.AlignLeft)
        self.listWidget_playlist_songs = QtWidgets.QListWidget(
            self.frame_playlist)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.listWidget_playlist_songs.setFont(font)
        self.listWidget_playlist_songs.setStyleSheet("color: #FFF;")
        self.listWidget_playlist_songs.setObjectName(
            "listWidget_playlist_songs")
        self.verticalLayout_11.addWidget(self.listWidget_playlist_songs)
        self.verticalLayout_13.addWidget(self.frame_playlist)
        self.Pages_Widget.addWidget(self.page_playlist_1)
        self.verticalLayout_4.addWidget(self.Pages_Widget)
        self.horizontalLayout.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        self.Player_field = QtWidgets.QFrame(self.centralwidget)
        self.Player_field.setMinimumSize(QtCore.QSize(0, 100))
        self.Player_field.setMaximumSize(QtCore.QSize(16777215, 120))
        self.Player_field.setStyleSheet("background-color: rgb(60, 60, 60);")
        self.Player_field.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Player_field.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Player_field.setObjectName("Player_field")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.Player_field)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_player_song_info = QtWidgets.QFrame(self.Player_field)
        self.frame_player_song_info.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_player_song_info.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_player_song_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_player_song_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_player_song_info.setObjectName("frame_player_song_info")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(
            self.frame_player_song_info)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_player_song_name = QtWidgets.QLabel(
            self.frame_player_song_info)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_player_song_name.setFont(font)
        self.label_player_song_name.setStyleSheet("color: #FFF;")
        self.label_player_song_name.setObjectName("label_player_song_name")
        self.verticalLayout_26.addWidget(self.label_player_song_name)
        self.label_player_artist_name = QtWidgets.QLabel(
            self.frame_player_song_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_player_artist_name.setFont(font)
        self.label_player_artist_name.setStyleSheet("color: rgb(180,180,180);")
        self.label_player_artist_name.setObjectName("label_player_artist_name")
        self.verticalLayout_26.addWidget(self.label_player_artist_name)
        self.horizontalLayout_11.addWidget(self.frame_player_song_info)
        self.frame_player_navigator = QtWidgets.QFrame(self.Player_field)
        self.frame_player_navigator.setStyleSheet("")
        self.frame_player_navigator.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_player_navigator.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_player_navigator.setObjectName("frame_player_navigator")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(
            self.frame_player_navigator)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_player_navigator_buttons = QtWidgets.QFrame(
            self.frame_player_navigator)
        self.frame_player_navigator_buttons.setFrameShape(
            QtWidgets.QFrame.StyledPanel)
        self.frame_player_navigator_buttons.setFrameShadow(
            QtWidgets.QFrame.Raised)
        self.frame_player_navigator_buttons.setObjectName(
            "frame_player_navigator_buttons")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(
            self.frame_player_navigator_buttons)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btn_player_navigator_repeat = QtWidgets.QPushButton(
            self.frame_player_navigator_buttons)
        self.btn_player_navigator_repeat.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_player_navigator_repeat.setStyleSheet("QPushButton {\n"
                                                       "    color: rgb(255,255,255);\n"
                                                       "    border: 0px solid;\n"
                                                       "    border-radius: 15px;\n"
                                                       "}\n"
                                                       "QPushButton:hover {\n"
                                                       "    background-color: rgb(85, 170, 255);\n"
                                                       "}")
        self.btn_player_navigator_repeat.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/repeat.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_player_navigator_repeat.setIcon(icon4)
        self.btn_player_navigator_repeat.setObjectName(
            "btn_player_navigator_repeat")
        self.horizontalLayout_9.addWidget(self.btn_player_navigator_repeat)
        self.btn_player_navigator_previous = QtWidgets.QPushButton(
            self.frame_player_navigator_buttons)
        self.btn_player_navigator_previous.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_player_navigator_previous.setStyleSheet("QPushButton {\n"
                                                         "    color: rgb(255,255,255);\n"
                                                         "    border: 0px solid;\n"
                                                         "    border-radius: 15px;\n"
                                                         "}\n"
                                                         "QPushButton:hover {\n"
                                                         "    background-color: rgb(85, 170, 255);\n"
                                                         "}")
        self.btn_player_navigator_previous.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/skip-back.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_player_navigator_previous.setIcon(icon5)
        self.btn_player_navigator_previous.setObjectName(
            "btn_player_navigator_previous")
        self.horizontalLayout_9.addWidget(self.btn_player_navigator_previous)
        self.btn_player_navigator_playPause = QtWidgets.QPushButton(
            self.frame_player_navigator_buttons)
        self.btn_player_navigator_playPause.setMinimumSize(
            QtCore.QSize(36, 36))
        self.btn_player_navigator_playPause.setStyleSheet("QPushButton {\n"
                                                          "    color: rgb(255,255,255);\n"
                                                          "    border: 0px solid;\n"
                                                          "    border-radius: 18px;\n"
                                                          "}\n"
                                                          "QPushButton:hover {\n"
                                                          "    background-color: rgb(85, 170, 255);\n"
                                                          "}")
        self.btn_player_navigator_playPause.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/play.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_player_navigator_playPause.setIcon(icon6)
        self.btn_player_navigator_playPause.setIconSize(QtCore.QSize(24, 24))
        self.btn_player_navigator_playPause.setObjectName(
            "btn_player_navigator_playPause")
        self.horizontalLayout_9.addWidget(self.btn_player_navigator_playPause)
        self.btn_player_navigator_forward = QtWidgets.QPushButton(
            self.frame_player_navigator_buttons)
        self.btn_player_navigator_forward.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_player_navigator_forward.setStyleSheet("QPushButton {\n"
                                                        "    color: rgb(255,255,255);\n"
                                                        "    border: 0px solid;\n"
                                                        "    border-radius: 15px;\n"
                                                        "}\n"
                                                        "QPushButton:hover {\n"
                                                        "    background-color: rgb(85, 170, 255);\n"
                                                        "}")
        self.btn_player_navigator_forward.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(
            ":/icons/icons/skip-forward.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_player_navigator_forward.setIcon(icon7)
        self.btn_player_navigator_forward.setObjectName(
            "btn_player_navigator_forward")
        self.horizontalLayout_9.addWidget(self.btn_player_navigator_forward)
        self.btn_player_navigator_shuffle = QtWidgets.QPushButton(
            self.frame_player_navigator_buttons)
        self.btn_player_navigator_shuffle.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_player_navigator_shuffle.setStyleSheet("QPushButton {\n"
                                                        "    color: rgb(255,255,255);\n"
                                                        "    border: 0px solid;\n"
                                                        "    border-radius: 15px;\n"
                                                        "}\n"
                                                        "QPushButton:hover {\n"
                                                        "    background-color: rgb(85, 170, 255);\n"
                                                        "}")
        self.btn_player_navigator_shuffle.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/shuffle.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_player_navigator_shuffle.setIcon(icon8)
        self.btn_player_navigator_shuffle.setObjectName(
            "btn_player_navigator_shuffle")
        self.horizontalLayout_9.addWidget(self.btn_player_navigator_shuffle)
        self.slider_player_navigator_progress_bar = Slider(
            self.frame_player_navigator_buttons)
        self.slider_player_navigator_progress_bar.setStyleSheet("QSlider::groove:horizontal { \n"
                                                                "    background-color: white;\n"
                                                                "    border: 0px solid #424242; \n"
                                                                "    height: 5px; \n"
                                                                "    border-radius: 2px;\n"
                                                                "}\n"
                                                                "\n"
                                                                "QSlider::handle:horizontal { \n"
                                                                "    background-color: #0d6efd; \n"
                                                                "    border: 2px solid #0d6efd; \n"
                                                                "    width: 8px; \n"
                                                                "    height: 10px; \n"
                                                                "    line-height: 10px; \n"
                                                                "    margin-top: -3px; \n"
                                                                "    margin-bottom: -3px; \n"
                                                                "    border-radius: 5px; \n"
                                                                "}\n"
                                                                "\n"
                                                                "QSlider::handle:horizontal:hover { \n"
                                                                "    border-radius: 5px;\n"
                                                                "}\n"
                                                                "\n"
                                                                "QSlider::sub-page:horizontal {\n"
                                                                "    background-color: #0d6efd;\n"
                                                                "}")
        self.slider_player_navigator_progress_bar.setOrientation(
            QtCore.Qt.Horizontal)
        self.slider_player_navigator_progress_bar.setObjectName(
            "slider_player_navigator_progress_bar")
        self.horizontalLayout_9.addWidget(
            self.slider_player_navigator_progress_bar)
        self.horizontalLayout_12.addWidget(self.frame_player_navigator_buttons)
        self.horizontalLayout_11.addWidget(self.frame_player_navigator)
        self.frame_player_volume = QtWidgets.QFrame(self.Player_field)
        self.frame_player_volume.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_player_volume.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_player_volume.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_player_volume.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_player_volume.setObjectName("frame_player_volume")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(
            self.frame_player_volume)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.slider_player_volume = Slider(self.frame_player_volume)
        self.slider_player_volume.setRange(0, 100)
        self.slider_player_volume.setStyleSheet("QSlider::groove:horizontal { \n"
                                                "    background-color: white;\n"
                                                "    border: 0px solid #424242; \n"
                                                "    border-radius: 5px;        \n"
                                                "    height: 10px; \n"
                                                "}\n"
                                                "\n"
                                                "QSlider::handle:horizontal { \n"
                                                "    background-color: #0d6efd; \n"
                                                "    border: 2px solid #0d6efd; \n"
                                                "    width: 16px; \n"
                                                "    height: 20px; \n"
                                                "    line-height: 20px; \n"
                                                "    margin-top: -5px; \n"
                                                "    margin-bottom: -5px; \n"
                                                "    border-radius: 10px; \n"
                                                "}\n"
                                                "\n"
                                                "QSlider::handle:horizontal:hover { \n"
                                                "    border-radius: 10px;\n"
                                                "}\n"
                                                "\n"
                                                "QSlider::sub-page:horizontal {\n"
                                                "    background-color: #0d6efd;\n"
                                                "    border-radius: 5px;\n"
                                                "}")
        self.slider_player_volume.setOrientation(QtCore.Qt.Horizontal)
        self.slider_player_volume.setObjectName("slider_player_volume")
        self.horizontalLayout_10.addWidget(self.slider_player_volume)
        self.horizontalLayout_11.addWidget(self.frame_player_volume)
        self.verticalLayout.addWidget(self.Player_field)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Pages_Widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_Dashboard.setText(_translate("MainWindow", "Dashboard"))
        self.Btn_Library.setText(_translate("MainWindow", "Library"))
        self.Btn_Add_Playlist.setText(_translate("MainWindow", "Add Playlist"))
        self.Btn_Settings.setText(_translate("MainWindow", "Settings"))
        self.label_dashboard.setText(_translate("MainWindow", "Dashboard"))
        self.Btn_menu_add_songs.setText(_translate("MainWindow", "Add songs"))
        self.Btn_menu_fer.setText(_translate(
            "MainWindow", "Emotion Recognition"))
        self.Btn_menu_settings.setText(_translate("MainWindow", "Settings"))
        self.label_emotion_recognition.setText(
            _translate("MainWindow", "Emotion recognition result"))
        self.label_fer_result.setText(_translate(
            "MainWindow", "Your current emotion is: Happy. Playing playlist: Playlist 1"))
        self.label_emotion_recognition_no_playlist.setText(
            _translate("MainWindow", "Emotion recognition result"))
        self.label_fer_result_no_playlist.setText(_translate("MainWindow", "Currently there is no playlist mapped for detected emotion. \n"
                                                             " Setup your preference now in Settings"))
        self.btn_go_to_settings_no_playlist.setText(
            _translate("MainWindow", "Go to settings"))
        self.label_emotion_recognition_loading.setText(
            _translate("MainWindow", "Emotion recognition"))
        self.label_emotion_recognition_info_loading.setText(
            _translate("MainWindow", "Detecting your emotion, please wait..."))
        self.label_dashboard_2.setText(_translate("MainWindow", "Settings"))
        self.Btn_settings_hand_gesture.setText(
            _translate("MainWindow", "Hand gesture"))
        self.Btn_settings_emotion_map.setText(
            _translate("MainWindow", "Emotion Playlist map"))
        self.Btn_settings_bluetooth.setText(
            _translate("MainWindow", "Bluetooth"))
        self.label_settings_hand_gesture_2.setText(
            _translate("MainWindow", "Emotion playlist map"))
        self.label_settings_emotion_playlist_map_happy.setText(
            _translate("MainWindow", "Happy"))
        self.label_settings_emotion_playlist_map_sad.setText(
            _translate("MainWindow", "Sad"))
        self.label_settings_emotion_playlist_map_angry.setText(
            _translate("MainWindow", "Angry"))
        self.label_settings_emotion_playlist_map_surprise.setText(
            _translate("MainWindow", "Surprise"))
        self.label_settings_emotion_playlist_map_neutral.setText(
            _translate("MainWindow", "Neutral"))
        self.label_settings_hand_gesture.setText(
            _translate("MainWindow", "Hand gesture setup"))
        self.btn_settings_enable_hand_gesture.setText(
            _translate("MainWindow", "Enable"))
        self.label_settings_bluetooth.setText(
            _translate("MainWindow", "Bluetooth setup"))
        self.btn_settings_bluetooth_scan_devices.setText(
            _translate("MainWindow", "Scan devices"))
        self.btn_settings_bluetooth_disconnect.setText(
            _translate("MainWindow", "Disconnect"))
        self.label_library.setText(_translate("MainWindow", "Library"))
        self.label_playlist_name.setText(
            _translate("MainWindow", "Playlist 1"))
        self.btn_playlist_play.setText(_translate("MainWindow", "Play"))
        self.btn_playlist_remove.setText(
            _translate("MainWindow", "Remove playlist"))
        self.label_player_song_name.setText(
            _translate("MainWindow", "Song name"))
        self.label_player_artist_name.setText(
            _translate("MainWindow", "Artist name"))

    def change_label_player_track_in_navigator(
        self,
        MainWindow,
        trackName: str = "Song name",
        artistName: str = "Artist name"
    ):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_player_song_name.setText(
            _translate("MainWindow", trackName))
        self.label_player_artist_name.setText(
            _translate("MainWindow", artistName))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
